sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sharmad6/testing-env-for-docker -f ./client/Dockerfile.dev ./client

after_success:
  - docker build -t sharmad6/multi-client ./client
  - docker build -t sharmad6/multi-nginx ./nginx
  - docker build -t sharmad6/multi-server ./server
  - docker build -t sharmad6/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sharmad6/multi-client
  - docker push sharmad6/multi-nginx
  - docker push sharmad6/multi-server
  - docker push sharmad6/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: 'us-east-2'
#   app: 'multi-docker'
#   env: 'MultiDocker-env'
#   bucket_name: 'elasticbeanstalk-us-east-2-263390996180'
#   bucket_path: 'multi-docker'
#   on: 
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY 
#   secret_access_key: $AWS_SECRET_KEY